### ISSUE TITLE
A binding is created when the pattern is _

### ISSUE THREAD

**Issue by sionescu** [VincentToups/shadchen#2]
This seems contrary to the documentation:

HECHEE-USER> (shadchen:match :foo (_ "FOO"))
; in: SHADCHEN:MATCH :FOO
;     (SHADCHEN::MATCH-HELPER #:MATCH-VALUE-NAME-1277
;       (HECHEE-USER::_ "FOO"))
; --> LET\* MULTIPLE-VALUE-LIST MULTIPLE-VALUE-CALL SHADCHEN::MATCH1 
; ==>
;   (LET ((HECHEE-USER::_ #:MATCH-VALUE-NAME-1277))
;     "FOO")
; 
; caught STYLE-WARNING:
;   The variable _ is defined but never used.
; 
; compilation unit finished
;   caught 1 STYLE-WARNING condition
"FOO"

**Comment by VincentToups** [comment]
Has to be shadchen:_

**Comment by VincentToups** [comment]
The documentation indeed fails to make that clear.
